# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uLesson' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uLesson

  target 'uLessonTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'SwiftLint'
  end

  target 'uLessonUITests' do
    # Pods for testing
  end

end
